require "env"
return {
  CoordinatorLayout,
  layout_width="fill",
  layout_height="fill",
  id="coordinator",
  {
    AppBarLayout,
    id="appBar",
    layout_width="fill",
    {
      MaterialToolbar,
      layout_width=-1,
      layout_scrollFlags=3,
      id="toolbar",
      title="PlaybackSettings";
    },
  },
  {
    NestedScrollView,
    layout_width="fill",
    layout_height="fill",
    layout_behavior="appbar_scrolling_view_behavior",
    fillViewport="true",
    {
      LinearLayoutCompat,
      orientation="vertical",
      layout_width="fill",
      layout_width="fill",
      {
        RecyclerView,
        layout_width="fill",
        id="recyclerView",
      },
    },
  },
}