require "env"
return{
  LinearLayoutCompat;
  orientation="vertical";
  layout_width="match_parent";
  {
    MaterialCardView;
    id="musicCard";
    StrokeColor=0,
    layout_width="match_parent";
    {
      LinearLayoutCompat;
      gravity="center";
      orientation="horizontal";
      layout_width="fill";
      {
        MaterialCardView;
        layout_width="50dp";
        layout_height="50dp";
        StrokeColor=0,
        radius="5dp";
        layout_marginLeft="20dp";
        {
          AppCompatImageView;
          layout_width=-1;
          layout_height=-1,
          id="p_cover";
        }
      };
      {
        LinearLayoutCompat;
        gravity="center|left";
        padding="10dp";
        paddingRight="15dp";
        layout_weight="1";
        orientation="vertical";
        layout_width="-1";
        {
          MaterialTextView;
          gravity="center";
          textSize="20sp";
          id="p_music";
          ellipsize="end";
          maxLines="1";
          text="Music";
        };
        {
          MaterialTextView;
          id="p_artist";
          text="artist";
          ellipsize="end";
          maxLines="1";
        };
      };
    };
  };
};