require "env"
return {
  LinearLayoutCompat;
  padding="0";
  orientation="vertical";
  layout_width="match_parent";
  {
    MaterialCardView;
    id="musicCard";
    StrokeColor=0,
    radius=0,
    layout_width="match_parent";
    {
      LinearLayoutCompat;
      gravity="center";
      orientation="horizontal";
      layout_width="fill";
      {
        LinearLayoutCompat;
        gravity="center|left";
        padding="10dp";
        layout_weight="1";
        orientation="vertical";
        layout_width="-1";
        {
          MaterialTextView;
          gravity="center";
          textSize="20sp";
          layout_marginLeft="10dp";
          id="music";
          ellipsize="end";
          maxLines="1";
          text="Music";
        };
        {
          MaterialTextView;
          layout_marginLeft="10dp";
          id="artist";
          text="artist";
          ellipsize="end";
          maxLines="1";
        };
      };
    };
  };
};